#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep  4 20:09:09 2024

@author: marielle
"""

text="CAGATTTGGTTGCGCGCATTGGTTGATTGGTTGGGTTGGTTGCGGATTGGTTGGAGGCACATTTGGTTGTCAGTTACGTTTGGTTGCTGTCTTGGTTGCTTGGTTGGTTGGTTGTTGGTTGGTGTTGGTTGTGATTGGTTGTTGGTTGTATTGGTTGTTGGTTGTTTGGTTGAACTCGTTGGTTGTCAATTGGTTGCCCCATTGGTTGAGTTGGTTGGAGGGTCATTGGTTGGTTGGTTGATTGGTTGCAAAATTGGTTGTTGGTTGTTGGTTGCTTTCGGTTACCATATTGGTTGTTGGTTGGAAGGTTGGTTGTATTTGGTTGTTGGTTGATTGGTTGTACATTTGGTTGACGATATCTTTGGTTGGCTTGGTTGGAGGCGCCTTCTTGGTTGCACCTTGGTTGCGGTATTGGTTGAACTCGCCTTGGTTGGGAGCCACTTTGGTTGGTTGGTTGCAGGTAGTTGGTTGTTTGGTTGTTGGTTGCGTTGGTTGCGTTTGGTTGGTTATTGGTTGGTTTGGTTGTTGCTTGGTTGAGCTTGGTTGATTGGGAGGTTGGTTGCTTGGTTGAAGTTGGTTGTTGGTTGCGTTTGGTTGTTGGTTGTTGGTTGATTGGTTGTTGGTTGATTGGTTGGTATCATGTTGGTTGAATTGGTTGTTGGTTGTTTTGGTTGTCTTGGTTGCTTTGGTTGTTGGTTGTGTTGGTTGTGGGTTTTGGTTGCCCTTGGTTGTCCTGTGGTTGGTTGAGTCAATTGGTTGAATTGGTTGGGATTTTTGGTTGCGCTTTGGTTGTTTGGTTGATTGGTTGTAAATTGGTTGTGTTCGTTGGTTGTTGGTTGTCTTGGTTGTTGGTTGAAGTAGTCTTGGTTGTTGGTTGCCTGGTGTTGGTTGTTGGTTGATCCCCCGAACATTGGTTGCTATTGTTTGGTTGGTTGGTTGATTGGTTGATTGGTTGTTGGTTGTTGGTTGGTTGGTTGTCTTGGTTGCTGTTGGTTGTGTGG"
pattern="TTGGTTGTT"

## Me trying the code first time
#def PatternCount(text, pattern):
    #count=0
    #for letter in text[letter:(length(text)-length(pattern)+1)]:
        #if text[letter:pattern+1] == pattern:
            #count+=1
    #return count

## Corrected way 
def PatternCount(text, pattern):
    count=0
    for i in range(len(text)-len(pattern)+1):
        if text[i:i+len(pattern)] == pattern:
            count+=1
    return count

count=PatternCount(text,pattern)
print(count)